### ISSUE TITLE
Como pecuarista, eu gostaria de manter os recursos envolvidos na criação do gado, para que eu possa melhor gerenciar tais recursos. 

### ISSUE THREAD

**Issue by reginaldo-re** [hmarcuzzo/cattle_control#25]
- [x] Criação da entidade Fazenda
- [x] Repositório de Fazenda
- [x] Camada de serviço para Fazenda
- [x] Testes da camada de serviços de Fazenda
- [x] View para listar fazendas 
- [x] View para adicionar e editar fazendas
- [x] Página para listar fazendas
- [x] Página para adicionar e editar fazendas
