### ISSUE TITLE
Como pecuarista, eu gostaria de registrar os gastos de cada boi, para que eu possa ter o controle de investimento de cada animal.

### ISSUE THREAD

**Issue by hmarcuzzo** [hmarcuzzo/cattle_control#7]
# Tipos de Gastos 
- [x] Criação da entidade de Tipos de Gastos
- [x] Repositório de Tipos de Gastos
- [x] Camada de serviço para Tipos de Gastos
- [x] Testes da camada de serviços de Tipos de Gastos

# Gastos
- [x] Criação da entidade de Gastos 
- [x] Repositório de Gastos
- [x] Camada de serviço para Gastos
- [x] Testes da camada de serviços de Gastos
- [x] View para listar Gastos
- [x] View para adicionar e editar Gastos
- [x] Página para listar Gastos
- [x] Página para adicionar e editar Gastos

# Gastos de Boi
- [x] Criação da entidade de Gastos de Boi
- [x] Repositório de Gastos de Boi
- [x] Camada de serviço para Gastos de Boi
- [x] Testes da camada de serviços de Gastos de Boi
- [x] View para listar Gastos de Boi
- [x] View para adicionar e editar Gastos de Boi
- [x] Página para listar Gastos de Boi
- [x] Página para adicionar e editar Gastos de Boi
